# Generated by Django 3.1.6 on 2021-03-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210311_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='isOrganization',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_organization',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
