# Generated by Django 3.1.6 on 2021-03-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210311_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='genre',
            field=models.CharField(choices=[('Annet', 'Annet'), ('Tur', 'Tur'), ('Løp', 'Lop')], default='Annet', max_length=5),
        ),
    ]
