# Generated by Django 3.1.6 on 2021-03-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210311_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='genre',
            field=models.CharField(choices=[('Annet', 'Annet'), ('Spasertur', 'Tur'), ('Løping', 'Lop')], default='Annet', max_length=10),
        ),
    ]
