# Generated by Django 3.1.6 on 2021-03-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210311_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='genre',
            field=models.CharField(choices=[('Annet', 'Annet'), ('Tur', 'Tur'), ('Løping', 'Lop'), ('Attraksjon', 'Attraksjon')], default='Annet', max_length=10),
        ),
    ]
