# Generated by Django 3.1.6 on 2021-03-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210315_1422'),
        ('api', '0009_auto_20210311_1834'),
    ]

    operations = [
    ]
