# Generated by Django 3.1.6 on 2021-03-25 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_organization', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default='')),
                ('date', models.DateTimeField()),
                ('genre', models.CharField(choices=[('Annet', 'Annet'), ('Tur', 'Tur'), ('Løping', 'Lop'), ('Attraksjon', 'Attraksjon')], default='Annet', max_length=10)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
                ('participants', models.ManyToManyField(blank=True, related_name='participants', to='api.UserProfile')),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
