# Generated by Django 3.1.6 on 2021-02-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default='')),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
